version: '3'
services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: docker-server/nginx
        # restart: always
        restart: unless-stopped
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./server_dev:/srv/docker-server
          - ./log:/var/log/nginx
          # 추가
          - ./cerbot/conf:/etc/letsencrypt
          - ./cerbot/www:/var/www/certbot
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        depends_on:
          - django

    certbot:
      container_name: certbot
      image: certbot/certbot:arm32v6-latest
      restart: unless-stopped
      volumes:
        - ./cerbot/conf:/etc/letsencrypt
        - ./cerbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


    django:
        container_name: django
        build: ./server_dev
        image: docker-server/django
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./server_dev:/srv/docker-server
          - ./log:/var/log/uwsgi

