# Generated by Django 4.2 on 2023-04-20 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variable",
                    models.CharField(help_text="축약하려는 단어", max_length=50, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbbreviatedVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abbreviated_variable",
                    models.CharField(help_text="축약된 단어", max_length=50),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abbreviatedVariables",
                        to="variable_abbreviation.variable",
                    ),
                ),
            ],
        ),
    ]
