# Generated by Django 4.2 on 2023-04-20 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variable_abbreviation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variables",
            old_name="variable",
            new_name="serached_variable",
        ),
    ]
