# Generated by Django 4.2 on 2023-04-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranslatedVariables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "korean_word",
                    models.CharField(help_text="한글로 입력한 단어", max_length=50),
                ),
                (
                    "translated_variable",
                    models.CharField(help_text="번역된 결과 단어", max_length=50),
                ),
            ],
            options={
                "managed": True,
            },
        ),
    ]
