# Generated by Django 4.2 on 2023-04-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variable_translation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatedvariables",
            name="korean_word",
            field=models.CharField(help_text="한글로 입력한 단어", max_length=50, unique=True),
        ),
    ]
