# Generated by Django 4.2 on 2023-04-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variable_translation", "0002_alter_translatedvariables_korean_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="translatedvariables",
            name="count",
            field=models.IntegerField(default=1, help_text="단어가 검색된 횟수"),
        ),
    ]
